// src/app/layout.tsx
import Navbar from "@/components/common/Navbar";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider";
import { SidebarProvider } from "@/context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Streamix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <SidebarProvider>
          <ReduxProvider>
            <Navbar />
            <Toaster position="bottom-left" />
            {children}
          </ReduxProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
